set_property PACKAGE_PIN H10 [get_ports {EMIF1_D[0]}]
set_property PACKAGE_PIN H9  [get_ports {EMIF1_D[1]}]
set_property PACKAGE_PIN E11 [get_ports {EMIF1_D[2]}]
set_property PACKAGE_PIN E10 [get_ports {EMIF1_D[3]}]
set_property PACKAGE_PIN F9  [get_ports {EMIF1_D[4]}]
set_property PACKAGE_PIN E9  [get_ports {EMIF1_D[5]}]
set_property PACKAGE_PIN D9  [get_ports {EMIF1_D[6]}]
set_property PACKAGE_PIN C9  [get_ports {EMIF1_D[7]}]
set_property PACKAGE_PIN D11 [get_ports {EMIF1_D[8]}]
set_property PACKAGE_PIN C11 [get_ports {EMIF1_D[9]}]
set_property PACKAGE_PIN C10 [get_ports {EMIF1_D[10]}]
set_property PACKAGE_PIN B10 [get_ports {EMIF1_D[11]}]
set_property PACKAGE_PIN B11 [get_ports {EMIF1_D[12]}]
set_property PACKAGE_PIN A10 [get_ports {EMIF1_D[13]}]
set_property PACKAGE_PIN B12 [get_ports {EMIF1_D[14]}]
set_property PACKAGE_PIN A12 [get_ports {EMIF1_D[15]}]
set_property PACKAGE_PIN B2  [get_ports {EMIF1_A[0]}]
set_property PACKAGE_PIN B3  [get_ports {EMIF1_A[1]}]
set_property PACKAGE_PIN D3  [get_ports {EMIF1_A[2]}]
set_property PACKAGE_PIN D4  [get_ports {EMIF1_A[3]}]
set_property PACKAGE_PIN F7  [get_ports {EMIF1_A[4]}]
set_property PACKAGE_PIN G7  [get_ports {EMIF1_A[5]}]
set_property PACKAGE_PIN A5  [get_ports {EMIF1_A[6]}]
set_property PACKAGE_PIN A6  [get_ports {EMIF1_A[7]}]
set_property PACKAGE_PIN G1  [get_ports {EMIF1_A[8]}]
set_property PACKAGE_PIN C3 [get_ports EMIF1_RAS_A]
set_property PACKAGE_PIN C4 [get_ports EMIF1_CAS_A]
set_property PACKAGE_PIN E5 [get_ports EMIF1_WEN_A]
set_property PACKAGE_PIN E6 [get_ports EMIF1_CLK_A]
set_property PACKAGE_PIN D6 [get_ports EPWM3A_A]
set_property PACKAGE_PIN D7 [get_ports EPWM3B_A]
set_property PACKAGE_PIN F5 [get_ports EPWM4A_A]
set_property PACKAGE_PIN G5 [get_ports EPWM4B_A]
set_property PACKAGE_PIN F8 [get_ports EPWM5A_A]
set_property PACKAGE_PIN G8 [get_ports EPWM5B_A]
set_property PACKAGE_PIN G6 [get_ports EPWM6A_A]
set_property PACKAGE_PIN H6 [get_ports EPWM6B_A]
# EPWM3 and EPWM4 B to 400pin connector for now 
# set_property PACKAGE_PIN H1 [get_ports EPWM3A_B]
# set_property PACKAGE_PIN B8 [get_ports EPWM3B_B]
# set_property PACKAGE_PIN C8 [get_ports EPWM4A_B]
# set_property PACKAGE_PIN B5 [get_ports EPWM4B_B]
# EPWM5 and EPWM6 B are LEDs for now 
# set_property PACKAGE_PIN C5 [get_ports EPWM5A_B]
# set_property PACKAGE_PIN A8 [get_ports EPWM5B_B]
# set_property PACKAGE_PIN A9 [get_ports EPWM6A_B]
# set_property PACKAGE_PIN B6 [get_ports EPWM6B_B]

# R5_0 DEBUG
set_property PACKAGE_PIN G11 [get_ports UART0_TX]
set_property PACKAGE_PIN H11 [get_ports UART0_RX]
# HSS1
set_property PACKAGE_PIN U6 [get_ports UART1_TX]
set_property PACKAGE_PIN Y7 [get_ports UART1_RX]
# HSS2
set_property PACKAGE_PIN AD5 [get_ports UART2_TX]
set_property PACKAGE_PIN AB5 [get_ports UART2_RX]
# DAP
set_property PACKAGE_PIN F12 [get_ports UART3_RX]
set_property PACKAGE_PIN G12 [get_ports UART3_TX]
set_property PACKAGE_PIN D12 [get_ports UART4_RX]
set_property PACKAGE_PIN E12 [get_ports UART4_TX]
# R5_1 DEBUG
set_property PACKAGE_PIN F10 [get_ports UART5_TX]
set_property PACKAGE_PIN G10 [get_ports UART5_RX]

set_property PACKAGE_PIN W7 [get_ports {PL64_1[0]}]
set_property PACKAGE_PIN W8 [get_ports {PL64_1[1]}]
set_property PACKAGE_PIN AA5 [get_ports {PL64_1[2]}]
set_property PACKAGE_PIN Y5 [get_ports {PL64_1[3]}]
set_property PACKAGE_PIN Y6 [get_ports {PL64_1[4]}]
set_property PACKAGE_PIN W6 [get_ports {PL64_1[5]}]
set_property PACKAGE_PIN AC3 [get_ports {PL64_1[6]}]
set_property PACKAGE_PIN AB3 [get_ports {PL64_1[7]}]
set_property PACKAGE_PIN AC4 [get_ports {PL64_1[8]}]
# set_property PACKAGE_PIN AB5 [get_ports {PL64[9]}]
set_property PACKAGE_PIN AE2 [get_ports {PL64_2[10]}]
set_property PACKAGE_PIN AD2 [get_ports {PL64_2[11]}]
set_property PACKAGE_PIN AD3 [get_ports {PL64_2[12]}]
set_property PACKAGE_PIN AD4 [get_ports {PL64_2[13]}]
set_property PACKAGE_PIN AE1 [get_ports {PL64_2[14]}]
set_property PACKAGE_PIN AD1 [get_ports {PL64_2[15]}]
set_property PACKAGE_PIN AE3 [get_ports {PL64_2[16]}]
set_property PACKAGE_PIN AE4 [get_ports {PL64_2[17]}]
set_property PACKAGE_PIN AA2 [get_ports {PL64_2[18]}]
set_property PACKAGE_PIN Y2 [get_ports {PL64_2[19]}]
set_property PACKAGE_PIN AC6 [get_ports {PL64_2[20]}]
set_property PACKAGE_PIN AB6 [get_ports {PL64_2[21]}]
set_property PACKAGE_PIN W2 [get_ports {PL64_2[22]}]
set_property PACKAGE_PIN W3 [get_ports {PL64_2[23]}]
set_property PACKAGE_PIN AB1 [get_ports {PL64_2[24]}]
set_property PACKAGE_PIN AB2 [get_ports {PL64_2[25]}]
set_property PACKAGE_PIN Y4 [get_ports {PL64_2[26]}]
set_property PACKAGE_PIN W4 [get_ports {PL64_2[27]}]
set_property PACKAGE_PIN Y1 [get_ports {PL64_2[28]}]
set_property PACKAGE_PIN W1 [get_ports {PL64_2[29]}]
set_property PACKAGE_PIN AA3 [get_ports {PL64_2[30]}]
set_property PACKAGE_PIN AA4 [get_ports {PL64_2[31]}]
set_property PACKAGE_PIN AD7 [get_ports {PL64_2[32]}]
set_property PACKAGE_PIN AD8 [get_ports {PL64_2[33]}]
set_property PACKAGE_PIN AE6 [get_ports {PL64_2[34]}]
set_property PACKAGE_PIN AE7 [get_ports {PL64_2[35]}]
set_property PACKAGE_PIN AE9 [get_ports {PL64_2[36]}]
set_property PACKAGE_PIN AD9 [get_ports {PL64_2[37]}]
#set_property PACKAGE_PIN AD5 [get_ports {PL64[38]}]
set_property PACKAGE_PIN AD6 [get_ports {PL64_3[39]}]
set_property PACKAGE_PIN AC8 [get_ports {PL64_3[40]}]
set_property PACKAGE_PIN AC9 [get_ports {PL64_3[41]}]
set_property PACKAGE_PIN AA8 [get_ports {PL64_3[42]}]
set_property PACKAGE_PIN AA9 [get_ports {PL64_3[43]}]
set_property PACKAGE_PIN AA7 [get_ports {PL64_3[44]}]
# set_property PACKAGE_PIN Y7 [get_ports {PL64_3[45]}]
set_property PACKAGE_PIN AB7 [get_ports {PL64_3[46]}]
set_property PACKAGE_PIN AB8 [get_ports {PL64_3[47]}]
set_property PACKAGE_PIN AC5 [get_ports {PL64_3[48]}]
set_property PACKAGE_PIN V5 [get_ports {PL64_3[49]}]
set_property PACKAGE_PIN AC1 [get_ports {PL64_3[50]}]
set_property PACKAGE_PIN V4 [get_ports {PL64_3[51]}]
set_property PACKAGE_PIN P6 [get_ports {PL65_1[0]}]
set_property PACKAGE_PIN P7 [get_ports {PL65_1[1]}]
set_property PACKAGE_PIN R4 [get_ports {PL65_1[2]}]
set_property PACKAGE_PIN P4 [get_ports {PL65_1[3]}]
set_property PACKAGE_PIN R5 [get_ports {PL65_1[4]}]
set_property PACKAGE_PIN R6 [get_ports {PL65_1[5]}]
set_property PACKAGE_PIN L3 [get_ports {PL65_1[6]}]
set_property PACKAGE_PIN M3 [get_ports DSP_CLK]
set_property PACKAGE_PIN N3 [get_ports {PL65_2[0]}]
set_property PACKAGE_PIN N4 [get_ports {PL65_2[1]}]
set_property PACKAGE_PIN J1 [get_ports {PL65_2[2]}]
set_property PACKAGE_PIN K1 [get_ports {PL65_2[3]}]
set_property PACKAGE_PIN M1 [get_ports {PL65_2[4]}]
set_property PACKAGE_PIN M2 [get_ports {PL65_2[5]}]
set_property PACKAGE_PIN J2 [get_ports {PL65_2[6]}]
set_property PACKAGE_PIN J3 [get_ports {PL65_2[7]}]
set_property PACKAGE_PIN K2 [get_ports {PL65_2[8]}]
set_property PACKAGE_PIN L2 [get_ports {PL65_2[9]}]
set_property PACKAGE_PIN L5 [get_ports {PL65_2[10]}]
set_property PACKAGE_PIN M6 [get_ports {PL65_2[11]}]
set_property PACKAGE_PIN R1 [get_ports {PL65_2[12]}]
set_property PACKAGE_PIN R2 [get_ports {PL65_2[13]}]
set_property PACKAGE_PIN M5 [get_ports {PL65_2[14]}]
set_property PACKAGE_PIN N5 [get_ports {PL65_2[15]}]
set_property PACKAGE_PIN K5 [get_ports {PL65_2[16]}]
set_property PACKAGE_PIN K6 [get_ports {PL65_2[17]}]
set_property PACKAGE_PIN K7 [get_ports {PL65_2[18]}]
set_property PACKAGE_PIN L7 [get_ports {PL65_2[19]}]
set_property PACKAGE_PIN J4 [get_ports {PL65_2[20]}]
set_property PACKAGE_PIN K4 [get_ports {PL65_2[21]}]
set_property PACKAGE_PIN J6 [get_ports {PL65_2[22]}]
set_property PACKAGE_PIN J7 [get_ports {PL65_2[23]}]
set_property PACKAGE_PIN V1 [get_ports {PL65_2[24]}]
set_property PACKAGE_PIN U1 [get_ports {PL65_2[25]}]
set_property PACKAGE_PIN P1 [get_ports {PL65_2[26]}]
set_property PACKAGE_PIN N1 [get_ports {PL65_2[27]}]
set_property PACKAGE_PIN V3 [get_ports {PL65_2[28]}]
set_property PACKAGE_PIN U3 [get_ports {PL65_2[29]}]
set_property PACKAGE_PIN P2 [get_ports {PL65_2[30]}]
set_property PACKAGE_PIN P3 [get_ports {PL65_2[31]}]
set_property PACKAGE_PIN U2 [get_ports {PL65_2[32]}]
set_property PACKAGE_PIN T3 [get_ports {PL65_2[33]}]
set_property PACKAGE_PIN U5 [get_ports {PL65_2[34]}]
# set_property PACKAGE_PIN U6 [get_ports {PL65_2[35]}]
set_property PACKAGE_PIN T7 [get_ports {PL65_2[36]}]
set_property PACKAGE_PIN R7 [get_ports {PL65_2[37]}]
set_property PACKAGE_PIN T4 [get_ports {PL65_2[38]}]
set_property PACKAGE_PIN T5 [get_ports {PL65_2[39]}]
set_property PACKAGE_PIN T2 [get_ports {PL65_2[40]}]
set_property PACKAGE_PIN U7 [get_ports {PL65_2[41]}]
set_property PACKAGE_PIN L4 [get_ports {PL65_2[42]}]
set_property PACKAGE_PIN M7 [get_ports {PL65_2[43]}]
set_property PACKAGE_PIN H3 [get_ports {PL66[0]}]
set_property PACKAGE_PIN H4 [get_ports {PL66[1]}]
set_property PACKAGE_PIN B1 [get_ports {PL66[2]}]
set_property PACKAGE_PIN C1 [get_ports {PL66[3]}]
set_property PACKAGE_PIN A2 [get_ports {PL66[4]}]
set_property PACKAGE_PIN A3 [get_ports {PL66[5]}]
set_property PACKAGE_PIN D1 [get_ports {PL66[6]}]
set_property PACKAGE_PIN D2 [get_ports {PL66[7]}]
set_property PACKAGE_PIN H5 [get_ports {PL66[8]}]
set_property PACKAGE_PIN A4 [get_ports {PL66[9]}]
set_property PACKAGE_PIN E7 [get_ports {PL66[10]}]
set_property PACKAGE_PIN D8 [get_ports {PL66[11]}]
# PL66[17:20]  to 400PIN
set_property PACKAGE_PIN H1 [get_ports {PL66_0[0]}]
set_property PACKAGE_PIN B8 [get_ports {PL66_0[1]}]
set_property PACKAGE_PIN C8 [get_ports {PL66_0[2]}]
set_property PACKAGE_PIN B5 [get_ports {PL66_0[3]}]
# PL66[21:24] LED
set_property PACKAGE_PIN C5 [get_ports {PL66_LED[0]}]
set_property PACKAGE_PIN A8 [get_ports {PL66_LED[1]}]
set_property PACKAGE_PIN A9 [get_ports {PL66_LED[2]}]
set_property PACKAGE_PIN B6 [get_ports {PL66_LED[3]}]
# PL66[25:28]
set_property PACKAGE_PIN C6 [get_ports {PL66_1[0]}]
set_property PACKAGE_PIN A7 [get_ports {PL66_1[1]}]
set_property PACKAGE_PIN B7 [get_ports {PL66_1[2]}]
set_property PACKAGE_PIN E4 [get_ports {PL66_1[3]}]
# PL66[32:34]
set_property PACKAGE_PIN F3 [get_ports {PL66_2[0]}]
set_property PACKAGE_PIN G3 [get_ports {PL66_2[1]}]
set_property PACKAGE_PIN F2 [get_ports {PL66_2[2]}]

set_property PACKAGE_PIN P12 [get_ports VN]
set_property PACKAGE_PIN N13 [get_ports VP]
set_property IOSTANDARD ANALOG [get_ports VN]
set_property IOSTANDARD ANALOG [get_ports VP]

# MIO12 TI0 BOOT SEL GPIO72 - default low
# set_property PACKAGE_PIN  AB11 [get_ports {TI_SEL0}]
# MIO23 TI1 BOOT SEL GPIO72 - default low
# set_property PACKAGE_PIN  V14 [get_ports {TI_SEL1}]
# set_property IOSTANDARD LVCMOS18 [get_ports TI_SEL0]
# set_property IOSTANDARD LVCMOS18 [get_ports TI_SEL1]

set_property IOSTANDARD LVCMOS33 [get_ports -of_objects [get_iobanks 44]]
set_property IOSTANDARD LVCMOS18 [get_ports -of_objects [get_iobanks 64]]
set_property IOSTANDARD LVCMOS18 [get_ports -of_objects [get_iobanks 65]]
set_property IOSTANDARD LVCMOS18 [get_ports -of_objects [get_iobanks 66]]

# set_property IOSTANDARD LVCMOS18 [get_ports -of_objects [get_iobanks 500]]
# set_property IOSTANDARD LVCMOS18 [get_ports -of_objects [get_iobanks 501]]
# set_property IOSTANDARD LVCMOS18 [get_ports -of_objects [get_iobanks 502]]
# set_property IOSTANDARD LVCMOS33 [get_ports -of_objects [get_iobanks 503]]
# set_property IOSTANDARD LVCMOS18 [get_ports -of_objects [get_iobanks 504]]
# set_property IOSTANDARD LVCMOS11 [get_ports -of_objects [get_iobanks 505]]

# HSS2_TX 07-2A6 OUT  BUF7-5/F7    PL64_38/AD5  
# HSS2_RX 08-1A7 IN   BUF8_6/F9    PL64_9/AB5
# HSS1_TX 10-1A2 OUT  BUF10_1/H15  PL65_43/U6
# HSS1_RX 09-2A4 IN   BUF9_3/G12   PL64-45/Y7
